"""
update_pokemon.py — run this to update fun facts and add all Gen 1 Pokemon

usage:
    python update_pokemon.py
"""

from app.database import engine, SessionLocal
from app.database import Base
from app.models.pokemon import Pokemon

ALL_POKEMON = [
    {"pokedex_number": 1,   "name": "Bulbasaur",   "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "Bulbasaur can survive for days using only the nutrients stored in the seed on its back. The seed grows larger as Bulbasaur absorbs more solar energy, and the aroma it releases can calm both Pokémon and people."},
    {"pokedex_number": 2,   "name": "Ivysaur",     "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "When Ivysaur's flower bud starts swelling, it can no longer stand on its hind legs due to the extra weight. The blossom releases a sweet aroma that intensifies when it is about to bloom."},
    {"pokedex_number": 3,   "name": "Venusaur",    "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "Venusaur's flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The scent from its flower can soothe people's emotions in battle."},
    {"pokedex_number": 4,   "name": "Charmander",  "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "The flame on the tip of Charmander's tail indicates how the Pokémon is feeling — if it burns brightly, Charmander is in good health. If the tail flame goes out, Charmander has died."},
    {"pokedex_number": 5,   "name": "Charmeleon",  "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Charmeleon relentlessly seeks opponents. When it finds a strong foe, it becomes excited and the flame at the tip of its tail blazes in a whitish-blue color."},
    {"pokedex_number": 6,   "name": "Charizard",   "primary_type": "Fire",     "secondary_type": "Flying",   "fun_fact": "Charizard flies around the sky in search of powerful opponents. Its fiery breath is capable of melting any material. If Charizard becomes truly angered, the flame at the tip of its tail burns in a light blue shade."},
    {"pokedex_number": 7,   "name": "Squirtle",    "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Squirtle's shell is not merely used for protection — its rounded shape and grooves on its surface help minimize water resistance to aid the Pokémon's swimming. It can shoot water with great accuracy."},
    {"pokedex_number": 8,   "name": "Wartortle",   "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Wartortle's tail is covered with a rich, thick fur that deepens in color with age. The tail is said to be a symbol of longevity, and it is very popular as a pet."},
    {"pokedex_number": 9,   "name": "Blastoise",   "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Blastoise has water spouts that protrude from its shell. These spouts are highly accurate and can shoot bullets of water with enough force to punch through thick steel plates."},
    {"pokedex_number": 10,  "name": "Caterpie",    "primary_type": "Bug",      "secondary_type": None,       "fun_fact": "Caterpie releases a horrific stench from its red antenna to repel enemies. It can devour leaves bigger than its body in a single day and grows incredibly fast."},
    {"pokedex_number": 11,  "name": "Metapod",     "primary_type": "Bug",      "secondary_type": None,       "fun_fact": "Metapod's shell is as hard as steel. It is said that inside the shell, Metapod is preparing for evolution — it is vulnerable to bird Pokémon that can peck through the shell."},
    {"pokedex_number": 12,  "name": "Butterfree",  "primary_type": "Bug",      "secondary_type": "Flying",   "fun_fact": "Butterfree has a superior ability to search for delicious honey from flowers. It can even find honey in a field of a million flowers. It rolls nectar into balls and carries them back."},
    {"pokedex_number": 13,  "name": "Weedle",      "primary_type": "Bug",      "secondary_type": "Poison",   "fun_fact": "Weedle has an extremely acute sense of smell and can distinguish its favorite foods from among 1,000 kinds of plants. The poison needle on its head is 2 cm long."},
    {"pokedex_number": 14,  "name": "Kakuna",      "primary_type": "Bug",      "secondary_type": "Poison",   "fun_fact": "Almost incapable of moving on its own, Kakuna remains stationary while it prepares for evolution inside its hard shell. The shell heats up when Kakuna is close to evolving."},
    {"pokedex_number": 15,  "name": "Beedrill",    "primary_type": "Bug",      "secondary_type": "Poison",   "fun_fact": "Beedrill is extremely territorial and will attack anything that approaches its nest. It moves at high speed and attacks using the large venomous stingers on its forelegs and abdomen."},
    {"pokedex_number": 16,  "name": "Pidgey",      "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Pidgey has a very docile nature and prefers to avoid conflict. Instead of fighting back, it sprays sand to blind its opponents. It is very popular among new trainers."},
    {"pokedex_number": 17,  "name": "Pidgeotto",   "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Pidgeotto claims a wide area as its own territory. It circles the skies and dives at prey at blistering speed. It is rarely found in cities."},
    {"pokedex_number": 18,  "name": "Pidgeot",     "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Pidgeot can fly at nearly the speed of sound and generate whirlwinds powerful enough to bend large trees just by spreading its wings. Its impressive plumage intimidates other Pokémon."},
    {"pokedex_number": 19,  "name": "Rattata",     "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Rattata is cautious in the extreme — even while it is asleep, it constantly moves its ears and reacts to the slightest sound. It is found in many environments and breeds very rapidly."},
    {"pokedex_number": 20,  "name": "Raticate",    "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Raticate's whiskers keep it balanced while running at incredible speeds. Its long front teeth are so sharp they can gnaw through concrete. It sends Rattata to scout out areas first."},
    {"pokedex_number": 21,  "name": "Spearow",     "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Spearow has a terrible cry that can be heard over half a mile away. It has a short attention span and cannot focus on one thing. It fights with other bird Pokémon over territory."},
    {"pokedex_number": 22,  "name": "Fearow",      "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Fearow can keep aloft without resting for almost an entire day. It uses its long neck and elongated beak to grab prey from both water and the ground without missing a beat."},
    {"pokedex_number": 23,  "name": "Ekans",       "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Ekans moves silently and stealthily through grass. It swallows its prey whole after unhinging its jaw. The older it gets, the longer it becomes."},
    {"pokedex_number": 24,  "name": "Arbok",       "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Arbok can crush a steel oil drum with its body. The frightening patterns on its belly have six variations, and the facial pattern on its belly paralyzes foes with fear."},
    {"pokedex_number": 25,  "name": "Pikachu",     "primary_type": "Electric", "secondary_type": None,       "fun_fact": "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy. When it is angered, it immediately discharges the energy stored in the pouches in its cheeks."},
    {"pokedex_number": 26,  "name": "Raichu",      "primary_type": "Electric", "secondary_type": None,       "fun_fact": "Raichu's tail serves as a ground to protect it from its own high-voltage power. It can shock itself if it lets too much electricity build up. Raichu that use too much electricity become withdrawn."},
    {"pokedex_number": 27,  "name": "Sandshrew",   "primary_type": "Ground",   "secondary_type": None,       "fun_fact": "Sandshrew lives in arid deserts and burrows into the sandy ground to sleep at night. When threatened, it curls into a ball with its rock-hard skin facing outward to defend itself."},
    {"pokedex_number": 28,  "name": "Sandslash",   "primary_type": "Ground",   "secondary_type": None,       "fun_fact": "Sandslash rolls into a ball and attacks by propelling itself at enemies. Its spines are made of the same substance as human fingernails and can be shed and regrown."},
    {"pokedex_number": 29,  "name": "Nidoran-F",   "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Nidoran♀ leads a quiet life away from others and rarely raises its voice. Despite its gentle appearance, the small horn on its forehead packs a powerful poison that can even kill large foes."},
    {"pokedex_number": 30,  "name": "Nidorina",    "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "When Nidorina is with a group of others, it becomes docile and rarely uses its claws or teeth. It prefers not to fight and will try to retreat when faced with danger."},
    {"pokedex_number": 31,  "name": "Nidoqueen",   "primary_type": "Poison",   "secondary_type": "Ground",   "fun_fact": "Nidoqueen is built to protect its young. Its hard scales provide strong protection, and it uses its entire body to slam enemies. It is incredibly caring toward its offspring."},
    {"pokedex_number": 32,  "name": "Nidoran-M",   "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Nidoran♂ has developed muscles for moving its ears. Thanks to them, it can move its ears in any direction and pick up even faint sounds from miles away."},
    {"pokedex_number": 33,  "name": "Nidorino",    "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Nidorino has a horn that is harder than a diamond. If it senses a hostile presence, all the barbs on its back bristle up at once and it challenges the foe with all its might."},
    {"pokedex_number": 34,  "name": "Nidoking",    "primary_type": "Poison",   "secondary_type": "Ground",   "fun_fact": "Nidoking uses its powerful tail to topple walls and knock down telephone poles. Once it goes on a rampage, there is no stopping it. A single swing of its mighty tail is enough to topple buildings."},
    {"pokedex_number": 35,  "name": "Clefairy",    "primary_type": "Fairy",    "secondary_type": None,       "fun_fact": "Clefairy is said to come from space. On nights with a full moon, Clefairy use moonlight to perform mysterious dances that leave footprints in the shape of stars."},
    {"pokedex_number": 36,  "name": "Clefable",    "primary_type": "Fairy",    "secondary_type": None,       "fun_fact": "Clefable moves by skipping lightly as if it were walking on air. It is rarely seen and dislikes noisy places. It can detect the sound of a pin dropping from half a mile away."},
    {"pokedex_number": 37,  "name": "Vulpix",      "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "At birth, Vulpix has one white tail that splits into six as it grows. Its six tails are full of fire. If it is attacked, it feigns weakness and then flames the distracted attacker."},
    {"pokedex_number": 38,  "name": "Ninetales",   "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Ninetales is said to live for 1,000 years. Legend has it that each of its nine tails contains a different mystical power. Grabbing one of its tails could cause a 1,000-year curse."},
    {"pokedex_number": 39,  "name": "Jigglypuff",  "primary_type": "Normal",   "secondary_type": "Fairy",    "fun_fact": "Jigglypuff's round body is filled with air. When it sings, it never pauses to breathe. If it can't finish its song, it inflates itself and rolls into its opponents in frustration."},
    {"pokedex_number": 40,  "name": "Wigglytuff",  "primary_type": "Normal",   "secondary_type": "Fairy",    "fun_fact": "Wigglytuff has large, soulful eyes and a body that can expand and deflate like a balloon. Its fine, silky fur is so pleasant to touch that anyone who feels it can't stop petting it."},
    {"pokedex_number": 41,  "name": "Zubat",       "primary_type": "Poison",   "secondary_type": "Flying",   "fun_fact": "Zubat has no eyes but navigates using ultrasonic waves emitted from its mouth. It avoids sunlight because it dislikes the drying effect. It is found in abundance in caves worldwide."},
    {"pokedex_number": 42,  "name": "Golbat",      "primary_type": "Poison",   "secondary_type": "Flying",   "fun_fact": "Golbat loves to drink blood and often drinks so much that it can't fly. Its large mouth can stretch wide enough to bite through a basketball."},
    {"pokedex_number": 43,  "name": "Oddish",      "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "During the day, Oddish buries itself in the ground to avoid sunlight and absorbs nutrients through its feet. At night, it wanders around and scatters its toxic pollen."},
    {"pokedex_number": 44,  "name": "Gloom",       "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "Gloom's drool is extraordinarily foul-smelling. However, some people claim the stench is attractive, making them feel hungry. The honey it drools is extremely sticky."},
    {"pokedex_number": 45,  "name": "Vileplume",   "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "Vileplume has the world's largest petals, which release a cloud of poisonous pollen with every step. The pollen is so poisonous that touching it can cause fainting."},
    {"pokedex_number": 46,  "name": "Paras",       "primary_type": "Bug",      "secondary_type": "Grass",    "fun_fact": "Paras is controlled by the mushrooms on its back — the mushrooms are parasitic fungi that have taken over its body. The mushrooms can be harvested and used as powerful medicine."},
    {"pokedex_number": 47,  "name": "Parasect",    "primary_type": "Bug",      "secondary_type": "Grass",    "fun_fact": "Parasect has been completely taken over by the parasitic mushroom on its back. The host's will has been entirely suppressed. The mushroom releases spores that induce sleep in foes."},
    {"pokedex_number": 48,  "name": "Venonat",     "primary_type": "Bug",      "secondary_type": "Poison",   "fun_fact": "Venonat's eyes function as radar and can see in the dark. Its entire body is covered with fine, stiff hair that provides protection against small bugs and poisons."},
    {"pokedex_number": 49,  "name": "Venomoth",    "primary_type": "Bug",      "secondary_type": "Poison",   "fun_fact": "The dustlike scales covering Venomoth's wings are loaded with toxins. Those scales are detached and scattered when it beats its wings. The toxic scales cause paralysis in anyone they touch."},
    {"pokedex_number": 50,  "name": "Diglett",     "primary_type": "Ground",   "secondary_type": None,       "fun_fact": "Diglett is raised underground and lives by eating the roots of plants. Nobody has ever seen the bottom half of Diglett's body — it is a great mystery even to scientists."},
    {"pokedex_number": 51,  "name": "Dugtrio",     "primary_type": "Ground",   "secondary_type": None,       "fun_fact": "Dugtrio are triplets born from one body. If one senses anything, the other two will also attack. Their burrowing loosens the ground so it's easier for plant roots to grow."},
    {"pokedex_number": 52,  "name": "Meowth",      "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Meowth is attracted to shiny objects and will wander about at night looking for coins and other items to bring back to its nest. The coin on its head glows when it spots something shiny."},
    {"pokedex_number": 53,  "name": "Persian",     "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Persian has six bold whiskers that give it a predatory look and help it sense air currents. Wealthy people keep it as a status symbol."},
    {"pokedex_number": 54,  "name": "Psyduck",     "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Psyduck is constantly headache-stricken, and the pain is so severe that it is always confused. It generates psychic power when the headache becomes intense enough — but it never remembers doing so."},
    {"pokedex_number": 55,  "name": "Golduck",     "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Golduck is the fastest swimmer of all Pokémon. When the gem on its forehead begins to glow mysteriously, it is said to be exhibiting strong psychic powers."},
    {"pokedex_number": 56,  "name": "Mankey",      "primary_type": "Fighting", "secondary_type": None,       "fun_fact": "Mankey lives in treetop groups. When it starts shaking and its nasal breathing turns rough, it's a sign that it is about to become violently enraged. Nobody knows what makes it so angry."},
    {"pokedex_number": 57,  "name": "Primeape",    "primary_type": "Fighting", "secondary_type": None,       "fun_fact": "Primeape becomes angry if you even glance at it. It chases anything that runs from it and never calms down. Scientists theorize that blood rushes to its head faster than it can be processed."},
    {"pokedex_number": 58,  "name": "Growlithe",   "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Growlithe has a superb sense of smell and is fiercely loyal to its trainer. It will bark and bite to repel intruders but is docile and gentle with its family and friends."},
    {"pokedex_number": 59,  "name": "Arcanine",    "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Arcanine is legendary in China for its beauty and speed. It is said to be capable of running over 6,200 miles in a single day and night. The fire within its body is what gives it its explosive speed."},
    {"pokedex_number": 60,  "name": "Poliwag",     "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Poliwag's skin is thin enough that its internal organs are visible through its belly. The spiral on its belly is actually its intestines showing through the translucent skin."},
    {"pokedex_number": 61,  "name": "Poliwhirl",   "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Poliwhirl can live both in water and on land. Staring at the swirling pattern on its belly causes drowsiness. Ancient people are said to have used it to help with insomnia."},
    {"pokedex_number": 62,  "name": "Poliwrath",   "primary_type": "Water",    "secondary_type": "Fighting", "fun_fact": "Poliwrath uses its highly developed muscles to swim and dive for extended periods. Its powerful legs allow it to walk against even the strongest ocean currents."},
    {"pokedex_number": 63,  "name": "Abra",        "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Abra sleeps 18 hours a day and can teleport in its sleep to escape danger. Because it uses telepathy to communicate, it has developed strong psychic powers but poor physical strength."},
    {"pokedex_number": 64,  "name": "Kadabra",     "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Kadabra emits alpha waves strong enough to induce headaches in those nearby. It is said that a fever caused by Kadabra's presence can be cured only by having Kadabra hold the patient's head."},
    {"pokedex_number": 65,  "name": "Alakazam",    "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Alakazam has a brain that continually grows — the IQ of a newly born Alakazam is 5,000. It remembers everything from birth and uses its spoons to amplify its psychic powers."},
    {"pokedex_number": 66,  "name": "Machop",      "primary_type": "Fighting", "secondary_type": None,       "fun_fact": "Machop's muscles are special — they never tire regardless of how much training it does. It can handle a hundred adults with ease and loves nothing more than working out."},
    {"pokedex_number": 67,  "name": "Machoke",     "primary_type": "Fighting", "secondary_type": None,       "fun_fact": "Machoke's thoroughly toned muscles possess the hardness of steel. Its power belt keeps its energy contained — without it, its power would be uncontrollable."},
    {"pokedex_number": 68,  "name": "Machamp",     "primary_type": "Fighting", "secondary_type": None,       "fun_fact": "Machamp can move its four arms simultaneously and incredibly fast. It can throw 500 punches in a single second and send an opponent flying over the horizon with a single hit."},
    {"pokedex_number": 69,  "name": "Bellsprout",  "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "Bellsprout's thin, whiplike body is very flexible. It can catch and eat insects despite its fragile appearance. Its root feet absorb moisture from the ground."},
    {"pokedex_number": 70,  "name": "Weepinbell",  "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "Weepinbell has a large hook on its rear end so it can hang from a tree branch while it waits for prey. If the hook becomes unhooked, it falls to the ground and crawls on its leaves."},
    {"pokedex_number": 71,  "name": "Victreebel",  "primary_type": "Grass",    "secondary_type": "Poison",   "fun_fact": "Victreebel lures prey into its mouth with a sweet aroma and then melts everything with its powerful digestive acid. Supposedly, the acid is so strong that anything that falls in dissolves instantly."},
    {"pokedex_number": 72,  "name": "Tentacool",   "primary_type": "Water",    "secondary_type": "Poison",   "fun_fact": "Tentacool is mostly water — 99% of its body consists of liquid. It floats on the surface of the sea and absorbs sunlight to convert it into beam attacks."},
    {"pokedex_number": 73,  "name": "Tentacruel",  "primary_type": "Water",    "secondary_type": "Poison",   "fun_fact": "Tentacruel has 80 tentacles that it can extend to entangle and immobilize prey. When it retracts them, the red orbs on its head glow and it fires ultrasonic waves."},
    {"pokedex_number": 74,  "name": "Geodude",     "primary_type": "Rock",     "secondary_type": "Ground",   "fun_fact": "Geodude is commonly found on mountain trails where it passes itself off as a stone. Hikers often trip over them. Its body is as hard as diamonds."},
    {"pokedex_number": 75,  "name": "Graveler",    "primary_type": "Rock",     "secondary_type": "Ground",   "fun_fact": "Graveler rolls down mountain paths without any regard for what's in the way. It rolls over everything in its path and doesn't stop until it hits something solid. It eats rocks as food."},
    {"pokedex_number": 76,  "name": "Golem",       "primary_type": "Rock",     "secondary_type": "Ground",   "fun_fact": "Golem rolls down steep mountain paths every year during molting season. The hard shell it sheds off is immediately snapped up by the locals who use the pieces to build walls."},
    {"pokedex_number": 77,  "name": "Ponyta",      "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Ponyta is born with very weak legs. But after it begins to walk and gallop, its legs grow stronger and faster. Its mane and tail contain incredibly hot flames that do not burn those Ponyta trusts."},
    {"pokedex_number": 78,  "name": "Rapidash",    "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Rapidash can gallop at nearly 150 mph. Its speed improves even more as it races against the wind. The flames it produces are so hot that its hooves glow like red-hot coals."},
    {"pokedex_number": 79,  "name": "Slowpoke",    "primary_type": "Water",    "secondary_type": "Psychic",  "fun_fact": "Slowpoke takes about 5 seconds to feel pain when it is bitten. It uses its tail as a fishing rod and waits for hours without moving. It never seems to be feeling any kind of urgency."},
    {"pokedex_number": 80,  "name": "Slowbro",     "primary_type": "Water",    "secondary_type": "Psychic",  "fun_fact": "Slowbro has a Shellder clamped onto its tail. The painful bite actually made Slowbro smarter than Slowpoke, but it also becomes more absent-minded the further the Shellder bites in."},
    {"pokedex_number": 81,  "name": "Magnemite",   "primary_type": "Electric", "secondary_type": "Steel",    "fun_fact": "Magnemite floats through the air using electromagnetic waves. It sticks to its Trainer's side as if it were a magnet and often causes massive power outages when feeding near power plants."},
    {"pokedex_number": 82,  "name": "Magneton",    "primary_type": "Electric", "secondary_type": "Steel",    "fun_fact": "Magneton emits a powerful magnetic force so strong that it makes compasses and electronic equipment go haywire. It is attracted to the north pole and is often found near power plants."},
    {"pokedex_number": 83,  "name": "Farfetchd",   "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Farfetch'd always carries a stalk of leek with it. Without the stalk, it becomes uneasy. Farfetch'd is so rare that it was nearly hunted to extinction."},
    {"pokedex_number": 84,  "name": "Doduo",       "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Doduo has two heads that alternate control of the body as they run. One head always watches for danger while the other rests. The two heads never think the same thing at once."},
    {"pokedex_number": 85,  "name": "Dodrio",      "primary_type": "Normal",   "secondary_type": "Flying",   "fun_fact": "Dodrio's three heads represent joy, sorrow, and anger. It is said never to sleep because at least one head is always awake. It can sprint faster than 40 mph."},
    {"pokedex_number": 86,  "name": "Seel",        "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Seel loves cold places and dislikes warm temperatures. It uses the sharp point on its head to break through ice floes in order to breathe. The colder the water, the more it thrives."},
    {"pokedex_number": 87,  "name": "Dewgong",     "primary_type": "Water",    "secondary_type": "Ice",      "fun_fact": "Dewgong loves to sleep on ice floes exposed to cold sunlight. The colder the temperature, the more energy it has. Its body is perfectly streamlined for swimming at high speed."},
    {"pokedex_number": 88,  "name": "Grimer",      "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Grimer was born when sludge in a dirty stream was exposed to X-rays from the Moon. It loves anything filthy and squeezes its amorphous body under doors to enter buildings."},
    {"pokedex_number": 89,  "name": "Muk",         "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Muk's body contains so many different toxic compounds that grass and plants will wither on contact. Its stench is so powerful it can be detected from over a mile away."},
    {"pokedex_number": 90,  "name": "Shellder",    "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Shellder spits out its large tongue to catch prey while its shell is clamped shut. It is very difficult to open the tightly-clamped shell."},
    {"pokedex_number": 91,  "name": "Cloyster",    "primary_type": "Water",    "secondary_type": "Ice",      "fun_fact": "Cloyster is impervious to most attacks while closed — even a bomb can't damage it. It attacks by opening its shell slightly and firing the spikes like bullets."},
    {"pokedex_number": 92,  "name": "Gastly",      "primary_type": "Ghost",    "secondary_type": "Poison",   "fun_fact": "Gastly is largely composed of gaseous matter and can surround an enemy with ease. A single Gastly can envelop an entire mansion in its gas cloud. Wind can blow it away."},
    {"pokedex_number": 93,  "name": "Haunter",     "primary_type": "Ghost",    "secondary_type": "Poison",   "fun_fact": "Haunter can lick anyone with its gaseous tongue and drain their life energy. Seeing one in the dark of night will cause an uncontrollable fit of shaking."},
    {"pokedex_number": 94,  "name": "Gengar",      "primary_type": "Ghost",    "secondary_type": "Poison",   "fun_fact": "Gengar is always lurking in the shadows. If you feel a sudden chill, it is certain that a Gengar appeared. It apparently wishes for a traveling companion and tries to create one by cursing humans."},
    {"pokedex_number": 95,  "name": "Onix",        "primary_type": "Rock",     "secondary_type": "Ground",   "fun_fact": "Onix tunnels through the ground at 50 mph while twisting and turning, which creates a trembling that can be felt from far away. The boulders it is made of become steadily rounder as it ages."},
    {"pokedex_number": 96,  "name": "Drowzee",     "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Drowzee puts enemies to sleep using a hypnotic wave from its hands, then eats their dreams. It can tell what a person has dreamed about by sniffing with its long nose."},
    {"pokedex_number": 97,  "name": "Hypno",       "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Hypno is always swinging its pendulum and will hypnotize anyone who meets its gaze. There are accounts of it causing people to follow it into the mountains and never return."},
    {"pokedex_number": 98,  "name": "Krabby",      "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Krabby lives on beaches, burrowed in sand. When it has nothing to eat, it will absorb nutrients by munching on sand. If you disturb one, it will grab you with its large claw and refuse to let go."},
    {"pokedex_number": 99,  "name": "Kingler",     "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Kingler's large, mighty claw can exert a force of 10,000 horsepower. However, the oversized claw is so heavy that Kingler has difficulty using it."},
    {"pokedex_number": 100, "name": "Voltorb",     "primary_type": "Electric", "secondary_type": None,       "fun_fact": "Voltorb was discovered when Poké Balls were invented. It closely resembles a Poké Ball but will shock anyone who tries to pick it up. It explodes at the slightest stimulation."},
    {"pokedex_number": 101, "name": "Electrode",   "primary_type": "Electric", "secondary_type": None,       "fun_fact": "Electrode eats electricity in the atmosphere and stores it in its body. When it has stored too much electricity, it becomes unstable and will explode suddenly without warning."},
    {"pokedex_number": 102, "name": "Exeggcute",   "primary_type": "Grass",    "secondary_type": "Psychic",  "fun_fact": "Exeggcute's six eggs are constantly communicating via telepathy. If the eggs are separated, they will seek out each other immediately."},
    {"pokedex_number": 103, "name": "Exeggutor",   "primary_type": "Grass",    "secondary_type": "Psychic",  "fun_fact": "Exeggutor's heads grow larger from exposure to strong sunlight and fall off when they get too heavy. The fallen heads continue to move and chant together."},
    {"pokedex_number": 104, "name": "Cubone",      "primary_type": "Ground",   "secondary_type": None,       "fun_fact": "Cubone wears the skull of its deceased mother on its head and never removes it. On the night of a full moon, it cries for its lost mother and the skull rattles in a sad lament."},
    {"pokedex_number": 105, "name": "Marowak",     "primary_type": "Ground",   "secondary_type": None,       "fun_fact": "Marowak overcame the grief of losing its mother by becoming tough and fearless. It uses its bone club as a weapon and boomerang. Its masked face is a symbol of its hardened spirit."},
    {"pokedex_number": 106, "name": "Hitmonlee",   "primary_type": "Fighting", "secondary_type": None,       "fun_fact": "Hitmonlee's legs can stretch twice their length when it is attacking. After battle, it massages its legs to relax the muscles. It can kick anything within reach from a standstill."},
    {"pokedex_number": 107, "name": "Hitmonchan",  "primary_type": "Fighting", "secondary_type": None,       "fun_fact": "Hitmonchan can punch a hundred times in two seconds. Its punches are so fast they create whirlwinds and can even pierce diamonds."},
    {"pokedex_number": 108, "name": "Lickitung",   "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Lickitung's tongue is twice the length of its body. It can extend its tongue quickly and use it to sense the texture and taste of everything in its environment."},
    {"pokedex_number": 109, "name": "Koffing",     "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Koffing floats through the air by constantly emitting toxic gases. The gases inside it react with each other and change daily."},
    {"pokedex_number": 110, "name": "Weezing",     "primary_type": "Poison",   "secondary_type": None,       "fun_fact": "Weezing is formed from two Koffing that merged together. The poisonous gases it generates are extremely toxic. It loves to suck up polluted air."},
    {"pokedex_number": 111, "name": "Rhyhorn",     "primary_type": "Ground",   "secondary_type": "Rock",     "fun_fact": "Rhyhorn charges straight ahead without looking where it is going. It knocks down anything in its path, even reinforced concrete. After the charge, it forgets why it was even charging."},
    {"pokedex_number": 112, "name": "Rhydon",      "primary_type": "Ground",   "secondary_type": "Rock",     "fun_fact": "Rhydon's horn can be rotated like a drill and is strong enough to bore through solid rock and even diamond."},
    {"pokedex_number": 113, "name": "Chansey",     "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Chansey lays nutritionally complete eggs every day. It will share its eggs with injured Pokémon or people. It is said that someone who finds a Chansey egg will have good luck for life."},
    {"pokedex_number": 114, "name": "Tangela",     "primary_type": "Grass",    "secondary_type": None,       "fun_fact": "Tangela's vines are covered with small, itchy hairs. No one has ever seen its true face. The vines snap off easily if grabbed and grow back the next day."},
    {"pokedex_number": 115, "name": "Kangaskhan",  "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Kangaskhan raises its young in the pouch on its belly for three years. When threatened, it stands up on its hind legs to look bigger."},
    {"pokedex_number": 116, "name": "Horsea",      "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Horsea wraps its tail around coral or rocks to anchor itself against currents. It blows powerful jets of water to propel itself and escape enemies."},
    {"pokedex_number": 117, "name": "Seadra",      "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Seadra can swim backward by rapidly flapping its fins and tail. It creates a whirlpool by swishing its tail and then jumps into the middle of the chaos to attack foes."},
    {"pokedex_number": 118, "name": "Goldeen",     "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Goldeen is a very beautiful Pokémon with fins that billow like an elegant dress. Despite its appearance, it is a fierce fighter with its powerful horn."},
    {"pokedex_number": 119, "name": "Seaking",     "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Seaking can swim up waterfalls using just the powerful movement of its fins. In autumn, the males compete for mates by showing off how beautifully they can spin in the water."},
    {"pokedex_number": 120, "name": "Staryu",      "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Staryu's center glows in a bright red color at night and can communicate with the stars by blinking its core. As long as the red core remains intact, Staryu can regenerate any lost limbs."},
    {"pokedex_number": 121, "name": "Starmie",     "primary_type": "Water",    "secondary_type": "Psychic",  "fun_fact": "Starmie's core shines in seven different colors and is said to be a gem from another world. It rotates its body rapidly to swim through the ocean at over 35 mph."},
    {"pokedex_number": 122, "name": "Mr. Mime",    "primary_type": "Psychic",  "secondary_type": "Fairy",    "fun_fact": "Mr. Mime is a master of pantomime and can create invisible walls out of thin air that are solid enough to stop any attack."},
    {"pokedex_number": 123, "name": "Scyther",     "primary_type": "Bug",      "secondary_type": "Flying",   "fun_fact": "Scyther moves so blindingly fast that it is nearly invisible. Its scythes are so sharp they can cut through thick logs with a single stroke. It never shows its back to an opponent."},
    {"pokedex_number": 124, "name": "Jynx",        "primary_type": "Ice",      "secondary_type": "Psychic",  "fun_fact": "Jynx sways and wiggles as if it is dancing. It can seize others with its gaze and make them feel compelled to dance along."},
    {"pokedex_number": 125, "name": "Electabuzz",  "primary_type": "Electric", "secondary_type": None,       "fun_fact": "Electabuzz moves faster than the eye can see and flickers electrical current through its body. If two Electabuzz grab each other in a fight, they can cause a city blackout."},
    {"pokedex_number": 126, "name": "Magmar",      "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Magmar blows out intensely hot flames from all over its body to intimidate its opponents. Its body temperature constantly reaches 2,200 degrees Fahrenheit."},
    {"pokedex_number": 127, "name": "Pinsir",      "primary_type": "Bug",      "secondary_type": None,       "fun_fact": "Pinsir grips prey with its powerful horns and won't let go. It can lift even the heaviest enemies overhead with its horns."},
    {"pokedex_number": 128, "name": "Tauros",      "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Tauros runs wild all over the place and will charge at anything it sees. Before attacking, it whips itself into a frenzy by lashing its body with its three tails."},
    {"pokedex_number": 129, "name": "Magikarp",    "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Magikarp is so weak that it cannot even withstand wind or rain. However, it can survive in the most polluted water. It secretly grows stronger as it endures hardship."},
    {"pokedex_number": 130, "name": "Gyarados",    "primary_type": "Water",    "secondary_type": "Flying",   "fun_fact": "Gyarados is capable of causing massive destruction and flooding that can last for a whole month. It has an extremely aggressive nature and was given the title 'the atrocious Pokémon'."},
    {"pokedex_number": 131, "name": "Lapras",      "primary_type": "Water",    "secondary_type": "Ice",      "fun_fact": "Lapras can understand human speech and loves to carry people on its back across the sea. It cries out in sorrow at night because its kind has been hunted close to extinction."},
    {"pokedex_number": 132, "name": "Ditto",       "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Ditto can transform into any Pokémon it sees. However, it has been known to imperfectly replicate faces from memory. Two Ditto that meet each other will stare at each other for a long time without ever transforming."},
    {"pokedex_number": 133, "name": "Eevee",       "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Eevee has an unstable genetic makeup that suddenly mutates due to the environment in which it lives. Radiation from various stones causes this Pokémon to evolve into one of eight different forms."},
    {"pokedex_number": 134, "name": "Vaporeon",    "primary_type": "Water",    "secondary_type": None,       "fun_fact": "Vaporeon's body has mutated to become closer to water, allowing it to melt into water and become undetectable. It can predict rain and disappears just before a shower begins."},
    {"pokedex_number": 135, "name": "Jolteon",     "primary_type": "Electric", "secondary_type": None,       "fun_fact": "Jolteon's body can generate 10,000 volts of electricity. Its fur can generate static electricity with each individual hair acting like a needle capable of discharging electricity."},
    {"pokedex_number": 136, "name": "Flareon",     "primary_type": "Fire",     "secondary_type": None,       "fun_fact": "Flareon's fluffy fur releases heat into the air. Its body temperature can reach up to 1,650 degrees Fahrenheit. Its internal fire organ breathes blasts of fire that can melt anything."},
    {"pokedex_number": 137, "name": "Porygon",     "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Porygon was the first artificial Pokémon ever created, made entirely from programming code. It is capable of moving through cyberspace and can be transmitted through computers around the world."},
    {"pokedex_number": 138, "name": "Omanyte",     "primary_type": "Rock",     "secondary_type": "Water",    "fun_fact": "Omanyte is an ancient Pokémon revived from a fossil. It once lived at the bottom of the sea and used its tentacles to move around."},
    {"pokedex_number": 139, "name": "Omastar",     "primary_type": "Rock",     "secondary_type": "Water",    "fun_fact": "Omastar is believed to have become extinct because its shell became too large and heavy, making it impossible to move quickly. It used its tentacles to catch prey."},
    {"pokedex_number": 140, "name": "Kabuto",      "primary_type": "Rock",     "secondary_type": "Water",    "fun_fact": "Kabuto is a Pokémon that has been regenerated from a fossil. While it was apparently believed to be extinct, a small colony was discovered alive at the base of Mt. Moon."},
    {"pokedex_number": 141, "name": "Kabutops",    "primary_type": "Rock",     "secondary_type": "Water",    "fun_fact": "Kabutops swam through ancient seas to hunt prey by slicing them apart with its sharp scythes. When it came to shore, its respiratory organs began to adapt for breathing air."},
    {"pokedex_number": 142, "name": "Aerodactyl",  "primary_type": "Rock",     "secondary_type": "Flying",   "fun_fact": "Aerodactyl is a ferocious Pokémon from the age of dinosaurs. It has fangs that are harder than diamond and flew the ancient skies, preying on even the largest dinosaurs."},
    {"pokedex_number": 143, "name": "Snorlax",     "primary_type": "Normal",   "secondary_type": None,       "fun_fact": "Snorlax's stomach is so strong it can digest any food — even if it's rotten or has thorns. It wakes up only to eat, consuming up to 900 pounds of food per day before going back to sleep."},
    {"pokedex_number": 144, "name": "Articuno",    "primary_type": "Ice",      "secondary_type": "Flying",   "fun_fact": "Articuno is a legendary bird Pokémon that can control ice. It is said to appear to doomed people who are lost in icy mountains, flying in the sky above them."},
    {"pokedex_number": 145, "name": "Zapdos",      "primary_type": "Electric", "secondary_type": "Flying",   "fun_fact": "Zapdos is a legendary bird Pokémon that has the ability to control electricity. It usually lives in thunderclouds and gains power by absorbing lightning bolts."},
    {"pokedex_number": 146, "name": "Moltres",     "primary_type": "Fire",     "secondary_type": "Flying",   "fun_fact": "Moltres is a legendary bird Pokémon that can control fire. It is said that its appearance indicates the end of winter and the beginning of spring."},
    {"pokedex_number": 147, "name": "Dratini",     "primary_type": "Dragon",   "secondary_type": None,       "fun_fact": "Dratini continually sheds its skin as it grows, and its entire shedded skin comes off in one piece. It was long considered a mythical Pokémon until a colony was found living underwater."},
    {"pokedex_number": 148, "name": "Dragonair",   "primary_type": "Dragon",   "secondary_type": None,       "fun_fact": "Dragonair stores an enormous amount of energy inside its body and can change the weather around it. Ancient people worshipped it as a god and believed sightings predicted rain or snow."},
    {"pokedex_number": 149, "name": "Dragonite",   "primary_type": "Dragon",   "secondary_type": "Flying",   "fun_fact": "Dragonite is capable of circling the globe in just 16 hours. It is a kindhearted Pokémon that guides ships through raging storms and rescues drowning people."},
    {"pokedex_number": 150, "name": "Mewtwo",      "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Mewtwo was created by a scientist after years of horrific gene-splicing and DNA-engineering experiments using Mew. It has the most savage heart among all Pokémon."},
    {"pokedex_number": 151, "name": "Mew",         "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people."},
    {"pokedex_number": 196, "name": "Espeon",      "primary_type": "Psychic",  "secondary_type": None,       "fun_fact": "Espeon is extremely loyal to any Trainer it considers worthy. To protect its Trainer from harm, it has developed precognitive powers using the fine hair that covers its body."},
    {"pokedex_number": 197, "name": "Umbreon",     "primary_type": "Dark",     "secondary_type": None,       "fun_fact": "Umbreon evolved as a result of exposure to the moon's waves. It hides quietly in the darkness and waits for its foes to make a move. The rings on its body glow when it leaps to attack."},
    {"pokedex_number": 249, "name": "Lugia",       "primary_type": "Psychic",  "secondary_type": "Flying",   "fun_fact": "Lugia's wings pack devastating power — a light fluttering of its wings can blow apart regular houses. As a result, Lugia spends its time deep at the bottom of the sea."},
    {"pokedex_number": 282, "name": "Gardevoir",   "primary_type": "Psychic",  "secondary_type": "Fairy",    "fun_fact": "Gardevoir has the ability to predict the future. If it senses impending danger to its Trainer, this Pokémon is said to unleash its psychokinetic energy at full power."},
    {"pokedex_number": 384, "name": "Rayquaza",    "primary_type": "Dragon",   "secondary_type": "Flying",   "fun_fact": "Rayquaza lived for hundreds of millions of years in the ozone layer, never descending to the ground. It puts an end to battles between Kyogre and Groudon."},
    {"pokedex_number": 445, "name": "Garchomp",    "primary_type": "Dragon",   "secondary_type": "Ground",   "fun_fact": "Garchomp can fly at speeds comparable to a jet plane, folding its body to minimize air resistance. It preys on bird Pokémon and can catch them mid-flight."},
    {"pokedex_number": 448, "name": "Lucario",     "primary_type": "Fighting", "secondary_type": "Steel",    "fun_fact": "Lucario can read the minds of others by sensing their aura waves. It understands the feelings of Pokémon and people through the reading of these waves."},
]


def run():
    db = SessionLocal()
    try:
        added = 0
        updated = 0
        for data in ALL_POKEMON:
            existing = db.query(Pokemon).filter(
                Pokemon.pokedex_number == data["pokedex_number"]
            ).first()

            if existing:
                existing.fun_fact = data["fun_fact"]
                existing.primary_type = data["primary_type"]
                existing.secondary_type = data["secondary_type"]
                updated += 1
            else:
                p = Pokemon(
                    pokedex_number=data["pokedex_number"],
                    name=data["name"],
                    primary_type=data["primary_type"],
                    secondary_type=data["secondary_type"],
                    fun_fact=data["fun_fact"],
                    description=data.get("description", ""),
                )
                db.add(p)
                added += 1

        db.commit()
        print(f"done! {updated} pokemon updated, {added} new pokemon added.")
    except Exception as e:
        db.rollback()
        print(f"error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    run()