"""add card_name to cards

Revision ID: 5dde7b50c9fa
Revises: 2b780c2eb51e
Create Date: 2026-04-24 12:13:50.777404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dde7b50c9fa'
down_revision: Union[str, Sequence[str], None] = '2b780c2eb51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'card_name')
    # ### end Alembic commands ###
