"""replace xendit fields with tripay fields

Revision ID: 7d70e8aa58e6
Revises: f19c5e305e9b
Create Date: 2026-04-29 17:12:52.317506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d70e8aa58e6'
down_revision: Union[str, Sequence[str], None] = 'f19c5e305e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tripay_reference', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('tripay_payment_url', sa.String(length=500), nullable=True))
    op.drop_column('orders', 'xendit_invoice_url')
    op.drop_column('orders', 'xendit_invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('xendit_invoice_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('xendit_invoice_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('orders', 'tripay_payment_url')
    op.drop_column('orders', 'tripay_reference')
    # ### end Alembic commands ###
