"""add bank fields to users

Revision ID: c559954e3394
Revises: c9dcd65ea5d6
Create Date: 2026-05-13 16:20:33.976930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c559954e3394'
down_revision: Union[str, Sequence[str], None] = 'c9dcd65ea5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bank_account_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_account_name')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'bank_name')
    # ### end Alembic commands ###
