"""add whatsapp to users

Revision ID: c9dcd65ea5d6
Revises: 7d70e8aa58e6
Create Date: 2026-04-30 17:25:43.407486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dcd65ea5d6'
down_revision: Union[str, Sequence[str], None] = '7d70e8aa58e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp')
    # ### end Alembic commands ###
