"""add xendit fields to orders

Revision ID: f19c5e305e9b
Revises: 5dde7b50c9fa
Create Date: 2026-04-26 17:01:20.927919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19c5e305e9b'
down_revision: Union[str, Sequence[str], None] = '5dde7b50c9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('xendit_invoice_id', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('xendit_invoice_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'xendit_invoice_url')
    op.drop_column('orders', 'xendit_invoice_id')
    # ### end Alembic commands ###
